language: objective-c
script:
    - xcodebuild test -project ACMECrypt/ACMECrypt.xcodeproj -scheme AMCEAssymTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c ; test ${PIPESTATUS[0]} -eq 0


